name: Push pipeline

concurrency:
  group: production
  cancel-in-progress: true

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - main

jobs:

  pre-build:
    name: Pre-build checks
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Compile types
        run: npm run typecheck

      - name: Run ESLint
        run: npm run lint

      - name: Check Prettier formatting
        run: npm run format:check

  migrations:
    name: Database migrations
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm install
          npm install --global vercel@latest

      - name: Pull environment variables
        run: vercel env pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Apply migrations
        run: npm run db:migrate

  deploy:
    name: Build and deploy
    environment:
      name: Production
      url: https://posts.nicholasly.com/
    runs-on: ubuntu-latest
    needs: [pre-build, migrations]
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install --global vercel@latest

      - name: Pull Vercel environment variables
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}